

class StateManager:
    # START_SCREEN
    # MAIN_MENU
    # LABYRINTH_ENTRANCE
    # LABYRINTH_SELECT
    # LABYRINTH_SELECTED
    # PARTY_CONFIRM
    # STAMINA_CONFIRM
    # PAINTING_SELECTION
    # COMBAT_SELECTED
    # IN_BATTLE
    # EXPLORATION_SELECTED
    # ONSLAUGHT_SELECTED
    # TREASURE_SELECTED
    # RESTORATION_SELECTED
    # BOSS_SELECTED
    # EXIT_LABYRINTH
    
    
    
    def __init__(self):
        pass


